Change/uc descriptions
gematik/ISiK-Medikation pull request #119
Opened 2024-04-19 13:47 UTC by MaxMTheilig

## Pull Request Short Cut

Umstrukturierung der Use Cases und Suchparameterbegründung wie besprochen

2024-06-25 14:23 UTC, lhitc requested changes
Syntax ist im Text fast durchgängig inkorrekt und muss korrigiert werden.

2024-06-25 14:23 UTC, lhitc commented on ImplementationGuide/markdown/Datenobjekte/Profile_AMTSBewertung.md
Warum soll dieser SP entfallen?
Wie soll im Zweifel nach einer Risikobeurteilung im Kontext einer bestimmten Erkrankung gesucht werden?

2024-06-25 14:23 UTC, lhitc commented on ImplementationGuide/markdown/Datenobjekte/Profile_AMTSBewertung.md
> +1. Der verkettete Suchparameter ```Patient:identifier``` unterstützt den Anwendungsfall:
patient:identifier, patient.identifier oder beides?

In jedem Fall stimmen Text und Beispiel nicht überein

2024-06-25 14:23 UTC, lhitc commented on ImplementationGuide/markdown/Datenobjekte/Profile_AMTSBewertung.md
> +1. Der verkettete Suchparameter ```Encounter:identifier``` unterstützt den Anwendungsfall:
Selbes Problem wie bei patient

2024-06-25 14:23 UTC, lhitc commented on ImplementationGuide/markdown/Datenobjekte/Profile_AMTSBewertung.md
> +1. Der verkettete Suchparameter ```Condition:code``` unterstützt den Anwendungsfall:
"Condition:code"? Hier sollte die Syntax wie im Beispiel benannt werden.

2024-06-25 14:23 UTC, lhitc commented on ImplementationGuide/markdown/Datenobjekte/Profile_Medikament.md
> +1. Der verkettete Suchparameter ```Ingredient:code``` unterstützt den Anwendungsfall:
Selbes Problem wie bei RiskAssessment condition

2024-06-25 14:23 UTC, lhitc commented on ImplementationGuide/markdown/Datenobjekte/Profile_Medikament.md
> +1. Der verkettete Suchparameter ```Ingredient:code``` unterstützt den Anwendungsfall:
Zieht sich unten weiter durch

2024-06-25 14:32 UTC, lhitc commented on ImplementationGuide/markdown/Datenobjekte/Profile_AMTSBewertung.md
erledigt, wurde nach unten verschoben

2024-06-25 14:34 UTC, lhitc commented on ImplementationGuide/markdown/Datenobjekte/Profile_AMTSBewertung.md
> +1. Der verkettete Suchparameter ```Patient:identifier``` unterstützt den Anwendungsfall:
angepasst

2024-06-25 18:44 UTC, f-peverali commented
> Syntax ist im Text fast durchgängig inkorrekt und muss korrigiert werden.

Entscheidende Frage für mich: sind hier breaking Changes drin oder Festlegungen, die wir nicht mehr in einem TC 4.0.1 unterbringen können? @lhitc ggf. auch @MaxMTheilig ?

2024-06-25 18:50 UTC, lhitc commented
Ich sehe hier keine breaking changes.

2024-06-25 19:26 UTC, patrick-werner approved these changes

2024-06-26 09:23 UTC, f-peverali commented
suggestion: da dies kein Breaking Change, kann es als TC später eingepflegt werden

2024-06-27 13:07 UTC, f-peverali commented on ImplementationGuide/markdown/UseCasesAnwendung/UseCases.md
> +## Zusammenhang zwischen verketteten Suchparametern und Use Cases
```suggestion
issue/question: diesen Abschnitt nochmal prüfen, da übergeordnete Festlegung in Stufe 4 Basis
```

2024-09-09 11:34 UTC, closed without merging