KBV Kommentare einpflegen
gematik/ISiK-Medikation pull request #123
Opened 2024-06-13 11:49 UTC by patrick-werner

fixes PTDATA-1028

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this IG / specification.
- [ ] My change requires a change to the documentation or narrative (intend) of the IG.
- [x] I have already updated the documentation / narrative (intend) accordingly.

2024-06-19 14:03 UTC, f-peverali requested changes
todo: grundsätzlich sollten MS und Kardinalitätem eine Begründung in Form eines Commenst haben - notfalls rein formal (s.u.), darf sich auch wiederholen.

praise: update der IPS Dependency guter Hinweis, der umgesetzt wurde

2024-06-19 14:03 UTC, f-peverali commented on Resources/input/fsh/ISiKMedikament.fsh
>        PZN 0..1 MS and
todo: hier bitte je Begründung für MS (ggf. auch Formal, wie : entspricht KBV PRofil XY)

2024-06-19 14:03 UTC, f-peverali commented on Resources/input/fsh/ISiKMedikament.fsh
>    * text MS
todo: s.o. zu MS

2024-06-19 14:03 UTC, f-peverali commented on Resources/input/fsh/ISiKMedikament.fsh
>    * denominator MS
issue: auch denominator sollte auf 1..1 gesetzt werden, oder?

2024-06-19 14:03 UTC, f-peverali commented on Resources/input/fsh/ISiKMedikament.fsh
>  * status 1..1 MS
todo: s.o. zu MS

2024-06-19 14:03 UTC, f-peverali commented on Resources/input/fsh/ISiKMedikament.fsh
>  * amount MS
todo: s.o. zu MS

2024-06-19 14:03 UTC, f-peverali commented on Resources/input/fsh/ISiKMedikament.fsh
>    * denominator MS
todo: s.o. zu MS

2024-06-19 14:03 UTC, f-peverali commented on Resources/input/fsh/ISiKMedikament.fsh
>  * ingredient MS
todo: s.o. zu MS

2024-06-25 09:44 UTC, patrick-werner commented on Resources/input/fsh/ISiKMedikament.fsh
>    * denominator MS
valider Punkt, wird angepasst

2024-06-26 10:53 UTC, f-peverali requested changes

2024-06-26 10:53 UTC, f-peverali commented on Resources/input/fsh/ISiKMedikament.fsh
>      * denominator MS
issue/question: hier auch 1..1 ?!

2024-06-26 10:56 UTC, f-peverali commented on ImplementationGuide/markdown/ReleaseNotes.md
> +- Entfernen der WG14 Kodierung, Hinzufügen eines SimpleQuantity Profiles, Update der Abhängigkeit auf IPS 1.1.0, Hinzufügen eines SCT Slices zu Medikationsoprofilen https://github.com/gematik/spec-IS
```suggestion
- Entfernen der WG14 Kodierung, Hinzufügen eines SimpleQuantity Profiles, Update der Abhängigkeit auf IPS 1.1.0, Hinzufügen eines SCT Slices zu Medikationsoprofilen, bei Medication.amount (Ratios) numerator und denominator auf 1..1 https://github.com/gematik/spec-ISiK-Medikation/pull/123
```

2024-06-26 11:04 UTC, patrick-werner commented on Resources/input/fsh/ISiKMedikament.fsh
>      * denominator MS
ja, wird angepasst

2024-06-26 11:11 UTC, f-peverali approved these changes

2024-06-26 11:11 UTC, merged