update requirements
gematik/ISiK-Medikation pull request #140
Opened 2024-10-31 08:38 UTC by f-peverali

# Contributor Pull Request

## Description
update requirements for MS reasonCode/reasonReference

## Motivation and Context
ANFISK-323

## How has this been tested?

## Snippets or Screenshots (if necessary):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this IG / specification.
- [ ] My change requires a change to the documentation or narrative (intend) of the IG.
- [x] I have already updated the documentation / narrative (intend) accordingly.

2024-10-31 08:40 UTC, f-peverali reviewed
suggestion: ggf. noch Hinweis für MedicationRequest (ohne MS)

2024-10-31 08:41 UTC, f-peverali commented on ImplementationGuide/markdown/ReleaseNotes.md
> +* Möglicher Breaking Change für Clients: Änderung (Schwächung) der MS-Definition für .reasonCode und reasonReference für MedicationAdministration und MedicationStatement
```suggestion
* Möglicher Breaking Change für Clients: Änderung (Schwächung) der MS-Definition für .reasonCode und reasonReference für MedicationAdministration und MedicationStatement https://github.com/gematik/spec-ISiK-Medikation/pull/140
```

2024-10-31 08:44 UTC, patrick-werner requested changes
siehe suggestion

2024-10-31 08:44 UTC, patrick-werner commented on Resources/fsh-generated/resources/StructureDefinition-ISiKMedikationsInformation.json
> +        "comment": "  Festlegung zum MS: Die Elemente .reasonCode und .reasonReference MÜSSEN nach OR-Logik in der Ausgabe verwendet werden, d.h. nur eines MUSS geliefert werden können. Weiterhin MÜS
```suggestion
        "comment": "  Festlegung zum MS: Die Elemente .reasonCode und .reasonReference MÜSSEN nach OR-Logik in der Ausgabe verwendet werden, d.h. mindestens Eines MUSS geliefert werden können. Weiterhin MÜSSEN beide Elemente interpretiert werden können.\n  \n  Begründung zu Must-Support: Konsolidierung mit MII.",
```

2024-10-31 09:08 UTC, f-peverali commented
> suggestion: ggf. noch Hinweis für MedicationRequest (ohne MS)

@lhitc könntest du hier bitte deinen Vorschlag für Stufe 4 einbringen?

2024-12-06 08:38 UTC, lhitc approved these changes

2024-12-12 14:59 UTC, f-peverali commented on ImplementationGuide/markdown/ReleaseNotes.md
> +* Möglicher Breaking Change für Clients: Änderung (Schwächung) der MS-Definition für .reasonCode und reasonReference für MedicationAdministration und MedicationStatement https://github.com/gematik/sp
```suggestion
* ´improve´ ´test modifying´ Möglicher Breaking Change für Clients: Änderung (Schwächung) der MS-Definition für .reasonCode und reasonReference für MedicationAdministration und MedicationStatement https://github.com/gematik/spec-ISiK-Medikation/pull/140
```

2024-12-12 15:04 UTC, merged